version: '3.8'

services:
  database:
    image: ignferry/bcr-database
    container_name: db-postgres
    ports: 
      - "5433:5432"
    environment:
      - POSTGRES_DB=bcr_management_dashboard
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend
      
  backend-server:
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: backend-server
    ports: 
      - "3000:3000"
    command: npm start
    environment:
      - DATABASE_URL=postgres://postgres:postgres@database:5432/bcr_management_dashboard?sslmode=disable
    networks:
      - backend
    depends_on:
      - database
      
networks:
  backend:
    driver: bridge
volumes:
  pgdata: